'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}
           
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.kundali': 'Kundali',
    'nav.numerology': 'Numerology',
    'nav.palmistry': 'Palmistry',
    'nav.consultation': 'Consultation',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.subscribe': 'Subscribe',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin Portal',
    'nav.profile': 'Profile',

    // Hero Section
    'hero.title1': 'Discover',
    'hero.title2': 'Your Destiny',
    'hero.subtitle': 'Unlock the secrets of the universe with personalized astrology, numerology, and expert guidance from renowned astrologers.',
    'hero.cta1': 'Get Free Kundali',
    'hero.cta2': 'Premium Features',
    'hero.stats1': 'Happy Users',
    'hero.stats2': 'Expert Astrologers',
    'hero.stats3': 'Years Experience',
    'hero.stats4': 'Accuracy',
    'hero.scroll': 'Explore More',

    // Features
    'features.title': 'Divine Services',
    'features.subtitle': 'Explore our comprehensive range of astrological services crafted to guide you through life\'s celestial journey with precision and wisdom',
    'feature1.title': 'Kundali Generator',
    'feature1.desc': 'Get your personalized birth chart with detailed planetary positions and accurate predictions based on Vedic astrology principles',
    'feature2.title': 'Numerology',
    'feature2.desc': 'Discover your life path, destiny, and soul urge numbers with comprehensive insights into your personality and future',
    'feature3.title': 'Palmistry Analysis',
    'feature3.desc': 'Upload your palm image for detailed analysis and accurate readings of your life lines and future predictions',
    'feature4.title': 'AI Astro Chat',
    'feature4.desc': 'Chat with our advanced AI astrologer anytime for instant cosmic guidance, daily horoscope, and personalized advice',
    'feature5.title': 'Talk to Astrologer',
    'feature5.desc': 'Connect with certified expert astrologers for personalized consultations via call, video, or chat sessions',
    'feature6.title': 'Book Pandit',
    'feature6.desc': 'Book experienced pandits for pujas, ceremonies, and rituals at your home with complete arrangements',
    'feature.explore': 'Explore Service',

    // Stats
    'stats.title': 'Trusted by Thousands',
    'stats.subtitle': 'Join our growing community of believers who have found guidance, clarity, and transformation',
    'stats.testimonials': 'What Our Clients Say',
    'stats.users': 'Satisfied Clients',
    'stats.astrologers': 'Expert Astrologers',
    'stats.predictions': 'Accurate Predictions',
    'stats.rate': 'Success Rate',

    // CTA
    'cta.title': 'Begin Your Cosmic Journey Today',
    'cta.subtitle': 'Join thousands of enlightened souls who have discovered their true path through our divine guidance and celestial insights',
    'cta.trial': 'Start Free Trial',
    'cta.consult': 'Consult Expert',
    'cta.secure': '100% Secure',
    'cta.available': '24/7 Available',
    'cta.trusted': 'Trusted Since',

    // Testimonials
    'testimonial1.name': 'Priya Sharma',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'The kundali analysis was incredibly accurate! It helped me understand my career path better.',
    'testimonial2.name': 'Rajesh Kumar',
    'testimonial2.role': 'Business Owner',
    'testimonial2.content': 'The numerology reading transformed my business decisions. Highly recommended!',
    'testimonial3.name': 'Anita Patel',
    'testimonial3.role': 'Teacher',
    'testimonial3.content': 'AI chat feature is amazing! Got instant answers to all my astrology questions.',

    // Kundali Page
    'kundali.title': 'Kundali Generator',
    'kundali.subtitle': 'Generate your comprehensive birth chart with detailed astrological insights',

    // Zodiac Signs
    'zodiac.aries': 'मेष',
    'zodiac.taurus': 'वृषभ',
    'zodiac.gemini': 'मिथुन',
    'zodiac.cancer': 'कर्क',
    'zodiac.leo': 'सिंह',
    'zodiac.virgo': 'कन्या',
    'zodiac.libra': 'तुला',
    'zodiac.scorpio': 'वृश्चिक',
    'zodiac.sagittarius': 'धनु',
    'zodiac.capricorn': 'मकर',
    'zodiac.aquarius': 'कुंभ',
    'zodiac.pisces': 'मीन',

    // Planets
    'planet.sun': 'सूर्य',
    'planet.moon': 'चंद्र',
    'planet.mars': 'मंगल',
    'planet.mercury': 'बुध',
    'planet.jupiter': 'गुरु',
    'planet.venus': 'शुक्र',
    'planet.saturn': 'शनि',
    'planet.rahu': 'राहु',
    'planet.ketu': 'केतु',

    // Other Dynamic Terms
    'benefic': 'हितकारी',
    'malefic': 'अहितकारी',
    'retrograde': 'वक्री',
    'strong': 'मजबूत',
    'weak': 'कमजोर',
    'verystrong': 'बहुत मजबूत',
    'average': 'औसत',
    'present': 'उपस्थित',
    'absent': 'अनुपस्थित',
    'active': 'सक्रिय',
    'inactive': 'निष्क्रिय',

    // Numerology Page
    'numerology.title': 'Numerology Calculator',
    'numerology.subtitle': 'Discover the hidden meanings in your name and birth date with comprehensive insights',
    'numerology.enterDetails': 'Enter Your Details',

    // Palmistry Page
    'palmistry.title': 'Palmistry Analysis',
    'palmistry.subtitle': 'Upload your palm image for comprehensive AI-powered insights and predictions',
    'palmistry.uploadTitle': 'Upload Palm Image',
    'palmistry.uploadText': 'Click to upload',
    'palmistry.uploadHint': 'PNG, JPG up to 10MB',
    'palmistry.changeImage': 'Click to change image',
    'palmistry.tipsTitle': 'Tips for Best Results:',
    'palmistry.tips1': '• Use natural bright lighting',
    'palmistry.tips2': '• Keep palm flat and straight',
    'palmistry.tips3': '• Capture entire palm clearly with fingers',
    'palmistry.tips4': '• Avoid shadows and reflections',
    'palmistry.tips5': '• Use clean, dry hands',
    'palmistry.analyzing': 'Analyzing palm...',
    'palmistry.analyze': 'Analyze Palm',
    'palmistry.noAnalysis': 'No Analysis Yet',
    'palmistry.noAnalysisDesc': 'Upload a palm image and click analyze to see detailed results',
    'palmistry.lifeLine': 'Life Line',
    'palmistry.heartLine': 'Heart Line',
    'palmistry.headLine': 'Head Line',
    'palmistry.fateLine': 'Fate Line',
    'palmistry.mountsAnalysis': 'Mounts Analysis',
    'palmistry.recommendations': 'Recommendations',
    'palmistry.predictions': 'Predictions:',
    'palmistry.length': 'Length:',
    'palmistry.depth': 'Depth:',
    'palmistry.clarity': 'Clarity:',
    'palmistry.shape': 'Shape:',
    'palmistry.position': 'Position:',
    'palmistry.presence': 'Presence:',
    'palmistry.overallAnalysis': 'Overall Analysis',

    // Palmistry Analysis Results (English)
    'palmistry.analysis.lifeLine.length': 'Long (extending to wrist)',
    'palmistry.analysis.lifeLine.depth': 'Deep and well-marked',
    'palmistry.analysis.lifeLine.clarity': 'Clear without breaks',
    'palmistry.analysis.lifeLine.meaning': 'Indicates exceptional vitality, robust health, and strong life force. You possess remarkable resilience and can enjoy a long, healthy life. The depth suggests physical stamina and endurance.',
    'palmistry.analysis.lifeLine.prediction1': 'Good health throughout life',
    'palmistry.analysis.lifeLine.prediction2': 'Strong immune system',
    'palmistry.analysis.lifeLine.prediction3': 'Quick recovery from illnesses',
    'palmistry.analysis.lifeLine.prediction4': 'High energy levels',
    'palmistry.analysis.heartLine.shape': 'Curved upward toward fingers',
    'palmistry.analysis.heartLine.position': 'High on palm',
    'palmistry.analysis.heartLine.clarity': 'Clear and unbroken',
    'palmistry.analysis.heartLine.meaning': 'Shows deep emotional depth, strong romantic inclinations, and passionate nature. You value relationships deeply and express emotions freely. The high position indicates idealistic love outlook.',
    'palmistry.analysis.heartLine.prediction1': 'Deep, meaningful relationships',
    'palmistry.analysis.heartLine.prediction2': 'Strong emotional bonds',
    'palmistry.analysis.heartLine.prediction3': 'Romantic and passionate nature',
    'palmistry.analysis.heartLine.prediction4': 'Loyalty in partnerships',
    'palmistry.analysis.headLine.clarity': 'Clear and well-defined',
    'palmistry.analysis.headLine.length': 'Long, extending across palm',
    'palmistry.analysis.headLine.curve': 'Slightly curved',
    'palmistry.analysis.headLine.meaning': 'Indicates sharp intellect, analytical thinking abilities, and strong decision-making capabilities. The length suggests comprehensive thinking and attention to detail. The slight curve shows balance between logic and creativity.',
    'palmistry.analysis.headLine.prediction1': 'Excellent problem-solving abilities',
    'palmistry.analysis.headLine.prediction2': 'Success in intellectual pursuits',
    'palmistry.analysis.headLine.prediction3': 'Strategic thinking',
    'palmistry.analysis.headLine.prediction4': 'Leadership potential',
    'palmistry.analysis.fateLine.presence': 'Present and strong',
    'palmistry.analysis.fateLine.clarity': 'Well-defined',
    'palmistry.analysis.fateLine.position': 'Running from wrist to middle finger',
    'palmistry.analysis.fateLine.meaning': 'Suggests clear life direction, career success, and strong sense of purpose. Your path is well-defined and you have natural ability to achieve goals. Strong fate line indicates self-made success.',
    'palmistry.analysis.fateLine.prediction1': 'Career advancement',
    'palmistry.analysis.fateLine.prediction2': 'Financial stability',
    'palmistry.analysis.fateLine.prediction3': 'Achievement of goals',
    'palmistry.analysis.fateLine.prediction4': 'Recognition in profession',
    'palmistry.analysis.mounts.jupiter.prominence': 'Well-developed',
    'palmistry.analysis.mounts.jupiter.meaning': 'Leadership, ambition, confidence',
    'palmistry.analysis.mounts.saturn.prominence': 'Balanced',
    'palmistry.analysis.mounts.saturn.meaning': 'Wisdom, discipline, responsibility',
    'palmistry.analysis.mounts.apollo.prominence': 'Prominent',
    'palmistry.analysis.mounts.apollo.meaning': 'Creativity, success, artistic talents',
    'palmistry.analysis.mounts.mercury.prominence': 'Moderate',
    'palmistry.analysis.mounts.mercury.meaning': 'Communication, business skills',
    'palmistry.analysis.mounts.venus.prominence': 'Full',
    'palmistry.analysis.mounts.venus.meaning': 'Love, passion, vitality',
    'palmistry.analysis.mounts.luna.prominence': 'Developed',
    'palmistry.analysis.mounts.luna.meaning': 'Imagination, intuition, sensitivity',
    'palmistry.analysis.fingerAnalysis.thumb': 'Strong and well-proportioned - indicates willpower and determination',
    'palmistry.analysis.fingerAnalysis.index': 'Long - shows leadership and ambition',
    'palmistry.analysis.fingerAnalysis.middle': 'Balanced - suggests stability and responsibility',
    'palmistry.analysis.fingerAnalysis.ring': 'Prominent - indicates creativity and desire for recognition',
    'palmistry.analysis.fingerAnalysis.pinky': 'Good length - shows communication skills',
    'palmistry.analysis.specialMarks.star': 'Brilliant success and recognition',
    'palmistry.analysis.specialMarks.triangle': 'Exceptional career achievement',
    'palmistry.analysis.specialMarks.moneyLine': 'Financial prosperity',
    'palmistry.analysis.overall': 'Your palmistry analysis reveals an exceptionally balanced and fortunate personality. Strong vitality combined with emotional depth and intellectual capabilities create a powerful foundation for success. The well-defined fate line and prominent mounts indicate clear life direction and multiple talents. You are naturally equipped for leadership, creative pursuits, and building deep relationships. Your palm suggests a life of achievement, good health, and emotional fulfillment.',
    'palmistry.analysis.recommendations.1': 'Focus on leadership roles in your career',
    'palmistry.analysis.recommendations.2': 'Develop your creative talents further',
    'palmistry.analysis.recommendations.3': 'Maintain work-life balance for optimal health',
    'palmistry.analysis.recommendations.4': 'Nurture your emotional relationships',
    'palmistry.analysis.recommendations.5': 'Trust your intuition in decision-making',

    // Consultation Page
    'consultation.title': 'Talk to Expert Astrologers',
    'consultation.subtitle': 'Get personalized guidance from certified astrologers via chat, call, or video consultation',
    'consultation.bookNow': 'Book Now',
    'consultation.howItWorks.title': 'How It Works',
    'consultation.howItWorks.subtitle': 'Simple steps to connect with expert astrologers',
    'consultation.steps.chooseService.title': 'Choose Service',
    'consultation.steps.chooseService.desc': 'Select chat, call, or video consultation',
    'consultation.steps.makePayment.title': 'Make Payment',
    'consultation.steps.makePayment.desc': 'Secure payment via Razorpay or QR code',
    'consultation.steps.getConnected.title': 'Get Connected',
    'consultation.steps.getConnected.desc': 'Instantly connect with an expert astrologer',
    'consultation.steps.receiveGuidance.title': 'Receive Guidance',
    'consultation.steps.receiveGuidance.desc': 'Get personalized cosmic insights and remedies',
    'consultation.sessionActive.title': 'Session Active!',
    'consultation.sessionActive.message': 'Your session is now active. An astrologer will join shortly.',
    'consultation.sessionActive.enterSession': 'Enter Session',
    'consultation.sessionActive.close': 'Close',
    'consultation.enterDetails': 'Enter Your Details',

    // Login Page
    'login.welcomeBack': 'Welcome Back',
    'login.subtitle': 'Sign in to access your cosmic insights',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.noAccount': 'Don\'t have an account?',
    'login.signUp': 'Sign up',
    'login.backToHome': '← Back to Home',

    // About Page
    'about.value1.title': 'Authenticity',
    'about.value1.desc': 'We provide genuine Vedic astrology services based on ancient wisdom and modern accuracy.',
    'about.value2.title': 'Community',
    'about.value2.desc': 'Join our growing community of seekers who have found guidance and transformation through astrology.',
    'about.value3.title': 'Excellence',
    'about.value3.desc': 'We maintain the highest standards in astrological practice, ensuring accurate and reliable predictions.',
    'about.value4.title': 'Compassion',
    'about.value4.desc': 'Every consultation is approached with empathy, understanding, and genuine care for your well-being.',
    'about.value5.title': 'Trust',
    'about.value5.desc': 'Your privacy and security are paramount, with all consultations conducted in complete confidence.',
    'about.value6.title': 'Innovation',
    'about.value6.desc': 'We blend traditional wisdom with modern technology to make astrology accessible and convenient.',
    'about.stats1': 'Happy Users',
    'about.stats2': 'Expert Astrologers',
    'about.stats3': 'Years Experience',
    'about.stats4': 'Accuracy Rate',
    'about.title': 'About Viprakarma',
    'about.subtitle': 'Your trusted companion for cosmic guidance and spiritual services',
    'about.missionTitle': 'Our Mission',
    'about.ourMission': 'At Viprakarma, we believe that understanding the cosmic forces that shape our lives can lead to better decisions, deeper self-awareness, and a more fulfilling existence. Our mission is to make authentic Vedic astrology and spiritual services accessible to everyone through modern technology while preserving the ancient wisdom of our traditions. We combine the precision of astronomical calculations with the insights of experienced astrologers to provide you with accurate, personalized guidance for every aspect of your life.',
    'about.valuesTitle': 'Our Values',
    'about.valuesSubtitle': 'The principles that guide everything we do',
    'about.storyTitle': 'Our Story',
    'about.ourStory': 'Viprakarma was born from a deep passion for Vedic astrology and a vision to make this ancient science accessible to the modern world. Our founders, experienced astrologers themselves, recognized the gap between traditional astrological consultations and the fast-paced digital age.\n\nWe assembled a team of certified astrologers, skilled developers, and design experts to create a platform that combines the best of both worlds - the profound wisdom of Vedic astrology and the convenience of modern technology.\n\nToday, we serve thousands of users worldwide, helping them navigate life\'s challenges with cosmic guidance. Whether it\'s career decisions, relationship questions, health concerns, or spiritual growth, we\'re here to illuminate your path with the light of astrological wisdom.',
  },
  hi: {
    // Navigation
    'nav.kundali': 'कुंडली',
    'nav.numerology': 'अंकशास्त्र',
    'nav.palmistry': 'हस्तरेखा शास्त्र',
    'nav.consultation': 'परामर्श',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'nav.subscribe': 'सब्स्क्राइब',
    'nav.login': 'लॉगिन',
    'nav.signup': 'साइन अप',
    'nav.logout': 'लॉगआउट',
    'nav.admin': 'एडमिन पोर्टल',
    'nav.profile': 'प्रोफाइल',

    // Hero Section
    'hero.title1': 'अपनी',
    'hero.title2': 'दैव नियति खोजें',
    'hero.subtitle': 'वैयक्तिक ज्योतिष, अंकशास्त्र और प्रसिद्ध ज्योतिषियों से विशेष मार्गदर्शन के साथ ब्रह्मांड के रहस्यों को अनलॉक करें।',
    'hero.cta1': 'मुफ्त कुंडली प्राप्त करें',
    'hero.cta2': 'प्रीमियम सुविधाएं',
    'hero.stats1': 'खुश उपयोगकर्ता',
    'hero.stats2': 'विशेषज्ञ ज्योतिषी',
    'hero.stats3': 'साल का अनुभव',
    'hero.stats4': 'सटीकता',
    'hero.scroll': 'और अधिक खोजें',

    // Features
    'features.title': 'दिव्य सेवाएं',
    'features.subtitle': 'हमारी व्यापक ज्योतिष सेवाओं की खोज करें जो जीवन की खगोलीय यात्रा में आपको सटीकता और बुद्धिमत्ता के साथ मार्गदर्शन करने के लिए तैयार की गई हैं',
    'feature1.title': 'कुंडली जनरेटर',
    'feature1.desc': 'वैदिक ज्योतिष सिद्धांतों के आधार पर विस्तृत ग्रहों की स्थिति और सटीक भविष्यवाणियों के साथ अपनी व्यक्तिगत जन्म कुंडली प्राप्त करें',
    'feature2.title': 'अंकशास्त्र',
    'feature2.desc': 'अपनी जीवन पथ संख्या, भाग्य संख्या और आत्मा की इच्छा संख्या की खोज करें साथ ही अपनी व्यक्तित्व और भविष्य में व्यापक अंतर्दृष्टि प्राप्त करें',
    'feature3.title': 'हस्तरेखा विश्लेषण',
    'feature3.desc': 'अपनी हथेली की छवि अपलोड करें विस्तृत विश्लेषण और अपनी जीवन रेखाओं और भविष्य की भविष्यवाणियों के सटीक पठन के लिए',
    'feature4.title': 'एआई एस्ट्रो चैट',
    'feature4.desc': 'हमारे उन्नत एआई ज्योतिषी से कभी भी चैट करें त्वरित ब्रह्मांडीय मार्गदर्शन, दैनिक कुंडली और व्यक्तिगत सलाह के लिए',
    'feature5.title': 'ज्योतिषी से बात करें',
    'feature5.desc': 'कॉल, वीडियो या चैट सत्रों के माध्यम से व्यक्तिगत परामर्श के लिए प्रमाणित विशेषज्ञ ज्योतिषियों से जुड़ें',
    'feature6.title': 'पंडित बुक करें',
    'feature6.desc': 'पूजा, समारोह और रिवाज के लिए अपने घर पर अनुभवी पंडितों को बुक करें पूर्ण व्यवस्था के साथ',
    'feature.explore': 'सेवा खोजें',

    // Stats
    'stats.title': 'हजारों लोगों द्वारा विश्वसनीय',
    'stats.subtitle': 'हमारे बढ़ते समुदाय में शामिल हों जहां लोगों ने मार्गदर्शन, स्पष्टता और परिवर्तन पाया है',
    'stats.testimonials': 'हमारे ग्राहक क्या कहते हैं',
    'stats.users': 'संतुष्ट ग्राहक',
    'stats.astrologers': 'विशेषज्ञ ज्योतिषी',
    'stats.predictions': 'सटीक भविष्यवाणियां',
    'stats.rate': 'सफलता दर',

    // CTA
    'cta.title': 'आज अपनी ब्रह्मांडीय यात्रा शुरू करें',
    'cta.subtitle': 'हजारों जागृत आत्माओं में शामिल हों जिन्होंने हमारे दिव्य मार्गदर्शन और ब्रह्मांडीय अंतर्दृष्टि के माध्यम से अपना सच्चा मार्ग खोजा है',
    'cta.trial': 'मुफ्त ट्रायल शुरू करें',
    'cta.consult': 'विशेषज्ञ से परामर्श करें',
    'cta.secure': '100% सुरक्षित',
    'cta.available': '24/7 उपलब्ध',
    'cta.trusted': 'विश्वसनीय तब से',

    // Testimonials
    'testimonial1.name': 'प्रिया शर्मा',
    'testimonial1.role': 'सॉफ्टवेयर इंजीनियर',
    'testimonial1.content': 'कुंडली विश्लेषण अविश्वसनीय रूप से सटीक था! इससे मेरी करियर पथ को समझने में मदद मिली।',
    'testimonial2.name': 'राजेश कुमार',
    'testimonial2.role': 'व्यापार मालिक',
    'testimonial2.content': 'अंकशास्त्र पठन ने मेरे व्यापारिक निर्णयों को बदल दिया। अत्यधिक अनुशंसित!',
    'testimonial3.name': 'अनीता पटेल',
    'testimonial3.role': 'शिक्षक',
    'testimonial3.content': 'एआई चैट सुविधा अद्भुत है! सभी ज्योतिष प्रश्नों के त्वरित उत्तर मिले।',

    // Kundali Page
    'kundali.title': 'कुंडली जनरेटर',
    'kundali.subtitle': 'विस्तृत ज्योतिषीय अंतर्दृष्टि के साथ अपनी व्यापक जन्म कुंडली तैयार करें',
    'kundali.birthDetails': 'जन्म विवरण',
    'kundali.fullName': 'पूरा नाम',
    'kundali.day': 'दिन',
    'kundali.month': 'माह',
    'kundali.year': 'साल',
    'kundali.hour': 'घंटा',
    'kundali.minute': 'मिनट',
    'kundali.ampm': 'AM/PM',
    'kundali.placeOfBirth': 'जन्म स्थान',
    'kundali.selectCity': 'एक शहर चुनें',
    'kundali.manualLocation': 'स्थान मैन्युअल रूप से दर्ज करें',
    'kundali.cityTown': 'शहर/गाँव',
    'kundali.latitude': 'अक्षांश',
    'kundali.longitude': 'देशांतर',
    'kundali.generateKundali': 'कुंडली तैयार करें',
    'kundali.generating': 'तैयार हो रहा है...',
    'kundali.saveKundali': 'कुंडली सहेजें',
    'kundali.saving': 'सहेज रहा है...',
    'kundali.exportPDF': 'PDF के रूप में निर्यात करें',
    'kundali.exporting': 'निर्यात हो रहा है...',
    'kundali.basicDetails': 'मूल विवरण',
    'kundali.sunSign': 'सूर्य राशि',
    'kundali.moonSign': 'चंद्र राशि',
    'kundali.ascendant': 'लग्न',
    'kundali.nakshatras': 'नक्षत्र',
    'kundali.sunNakshatra': 'सूर्य नक्षत्र:',
    'kundali.moonNakshatra': 'चंद्र नक्षत्र:',
    'kundali.ascendantNakshatra': 'लग्न नक्षत्र:',
    'kundali.pada': 'पदा:',
    'kundali.characteristics': 'विशेषताएँ:',
    'kundali.planetaryPositions': 'ग्रहों की स्थिति',
    'kundali.benefic': 'हितकारी',
    'kundali.malefic': 'अहितकारी',
    'kundali.sign': 'राशि:',
    'kundali.house': 'घर:',
    'kundali.degree': 'डिग्री:',
    'kundali.nakshatra': 'नक्षत्र:',
    'kundali.retrograde': 'वक्री',
    'kundali.planetaryStrengths': 'ग्रहों की शक्तियाँ',
    'kundali.status': 'स्थिति:',
    'kundali.strengthPercent': 'शक्ति प्रतिशत:',
    'kundali.shadbala': 'षड्बल:',
    'kundali.currentDasha': 'वर्तमान दशा अवधि',
    'kundali.mahadasha': 'महादशा',
    'kundali.level': 'स्तर:',
    'kundali.period': 'अवधि:',
    'kundali.upcomingMahadashas': 'आगामी महादशाएँ',
    'kundali.auspiciousYogas': 'शुभ योग',
    'kundali.strength': 'शक्ति:',
    'kundali.planets': 'ग्रह:',
    'kundali.doshasMalefic': 'दोष और अहितकारी प्रभाव',
    'kundali.present': 'उपस्थित',
    'kundali.absent': 'अनुपस्थित',
    'kundali.active': 'सक्रिय',
    'kundali.inactive': 'निष्क्रिय',
    'kundali.mangalDosha': 'मंगल दोष',
    'kundali.kalSarpDosha': 'काल सर्प दोष',
    'kundali.pitruDosha': 'पितृ दोष',
    'kundali.sadeSati': 'साढ़े साती',
    'kundali.lifePredictions': 'जीवन भविष्यवाणियाँ',
    'kundali.personality': 'व्यक्तित्व',
    'kundali.career': 'करियर',
    'kundali.finance': 'वित्त',
    'kundali.health': 'स्वास्थ्य',
    'kundali.marriage': 'विवाह और संबंध',
    'kundali.education': 'शिक्षा',
    'kundali.recommendedRemedies': 'अनुशंसित उपाय',
    'kundali.note': 'नोट:',
    'kundali.namePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'kundali.dayPlaceholder': 'DD',
    'kundali.monthPlaceholder': 'MM',
    'kundali.yearPlaceholder': 'YYYY',
    'kundali.hourPlaceholder': 'HH',
    'kundali.minutePlaceholder': 'MM',
    'kundali.cityPlaceholder': 'एक शहर चुनें',
    'kundali.manualCityPlaceholder': 'शहर या गाँव का नाम दर्ज करें',
    'kundali.mangalDoshaDesc': 'मंगल 1वें, 4वें, 7वें, 8वें या 12वें घर में स्थित है। विशेष उपाय अनुशंसित हैं।',
    'kundali.mangalDoshaAbsent': 'आपकी कुंडली में मंगल दोष उपस्थित नहीं है।',
    'kundali.kalSarpDoshaDesc': 'सभी ग्रह राहु और केतु के बीच फंसे हुए हैं। विशेष पूजा अनुशंसित हैं।',
    'kundali.kalSarpDoshaAbsent': 'आपकी कुंडली में काल सर्प दोष उपस्थित नहीं है।',
    'kundali.pitruDoshaDesc': 'पूर्वजों से संबंधित मुद्दे वर्तमान जीवन को प्रभावित कर सकते हैं। नियमित तर्पण अनुशंसित है।',
    'kundali.pitruDoshaAbsent': 'आपकी कुंडली में पितृ दोष उपस्थित नहीं है।',
    'kundali.sadeSatiDesc': 'शनि चंद्र राशि के माध्यम से पारगमन कर रहा है। परीक्षण और विकास की अवधि।',
    'kundali.sadeSatiInactive': 'साढ़े साती अवधि वर्तमान में निष्क्रिय है।',
    'kundali.remedyNote': 'ये उपाय आपके जन्म कुंडली के आधार पर सामान्य सुझाव हैं। व्यक्तिगत मार्गदर्शन के लिए योग्य ज्योतिषी से परामर्श करें और इन उपायों को ठीक से लागू करें।',

    // Numerology Page
    'numerology.title': 'अंकशास्त्र कैलकुलेटर',
    'numerology.subtitle': 'अपने नाम और जन्म तिथि में छिपे अर्थों की खोज करें',
    'numerology.enterDetails': 'अपनी जानकारी दर्ज करें',

    // Consultation Page
    'consultation.title': 'विशेषज्ञ ज्योतिषियों से बात करें',
    'consultation.subtitle': 'चैट, कॉल या वीडियो परामर्श के माध्यम से प्रमाणित ज्योतिषियों से व्यक्तिगत मार्गदर्शन प्राप्त करें',
    'consultation.bookNow': 'अभी बुक करें',
    'consultation.howItWorks.title': 'यह कैसे काम करता है',
    'consultation.howItWorks.subtitle': 'विशेषज्ञ ज्योतिषियों से जुड़ने के सरल चरण',
    'consultation.steps.chooseService.title': 'सेवा चुनें',
    'consultation.steps.chooseService.desc': 'चैट, कॉल या वीडियो परामर्श चुनें',
    'consultation.steps.makePayment.title': 'भुगतान करें',
    'consultation.steps.makePayment.desc': 'रेजरपे या क्यूआर कोड के माध्यम से सुरक्षित भुगतान',
    'consultation.steps.getConnected.title': 'जुड़ें',
    'consultation.steps.getConnected.desc': 'तुरंत एक विशेषज्ञ ज्योतिषी से जुड़ें',
    'consultation.steps.receiveGuidance.title': 'मार्गदर्शन प्राप्त करें',
    'consultation.steps.receiveGuidance.desc': 'व्यक्तिगत ब्रह्मांडीय अंतर्दृष्टि और उपाय प्राप्त करें',
    'consultation.sessionActive.title': 'सत्र सक्रिय!',
    'consultation.sessionActive.message': 'आपका सत्र अब सक्रिय है। एक ज्योतिषी जल्द ही जुड़ जाएगा।',
    'consultation.sessionActive.enterSession': 'सत्र में प्रवेश करें',
    'consultation.sessionActive.close': 'बंद करें',
    'consultation.enterDetails': 'अपनी जानकारी दर्ज करें',

    // Login Page
    'login.welcomeBack': 'वापसी पर स्वागत है',
    'login.subtitle': 'अपनी ब्रह्मांडीय अंतर्दृष्टि तक पहुंचने के लिए साइन इन करें',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.signIn': 'साइन इन',
    'login.signingIn': 'साइन इन हो रहा है...',
    'login.noAccount': 'कोई खाता नहीं है?',
    'login.signUp': 'साइन अप',
    'login.backToHome': '← होम पर वापस जाएं',

    // Consultation Page
    'consultation.title': 'हमारे विशेषज्ञ पंडितों से बात करें',
    'consultation.subtitle': 'जीवन, करियर, रिश्तों और आध्यात्मिक मामलों पर व्यक्तिगत मार्गदर्शन के लिए अनुभवी वैदिक विद्वानों और ज्योतिषियों से जुड़ें।',

    // Palmistry Page
    'palmistry.title': 'हस्तरेखा विश्लेषण',
    'palmistry.subtitle': 'अपनी हथेली की छवि अपलोड करें व्यापक एआई-संचालित अंतर्दृष्टि और भविष्यवाणियों के लिए',
    'palmistry.uploadTitle': 'हथेली छवि अपलोड करें',
    'palmistry.uploadText': 'अपलोड करने के लिए क्लिक करें',
    'palmistry.uploadHint': 'PNG, JPG 10MB तक',
    'palmistry.changeImage': 'छवि बदलने के लिए क्लिक करें',
    'palmistry.tipsTitle': 'सर्वोत्तम परिणामों के लिए युक्तियाँ:',
    'palmistry.tips1': '• प्राकृतिक उज्ज्वल प्रकाश का उपयोग करें',
    'palmistry.tips2': '• हथेली को सपाट और सीधा रखें',
    'palmistry.tips3': '• उंगलियों के साथ पूरी हथेली को स्पष्ट रूप से कैप्चर करें',
    'palmistry.tips4': '• छाया और प्रतिबिंब से बचें',
    'palmistry.tips5': '• Use clean, dry hands',
    'palmistry.analyzing': 'हथेली का विश्लेषण हो रहा है...',
    'palmistry.analyze': 'हथेली का विश्लेषण करें',
    'palmistry.noAnalysis': 'अभी तक कोई विश्लेषण नहीं',
    'palmistry.noAnalysisDesc': 'विस्तृत परिणाम देखने के लिए हथेली की छवि अपलोड करें और विश्लेषण पर क्लिक करें',
    'palmistry.lifeLine': 'जीवन रेखा',
    'palmistry.heartLine': 'हृदय रेखा',
    'palmistry.headLine': 'मस्तिष्क रेखा',
    'palmistry.fateLine': 'भाग्य रेखा',
    'palmistry.mountsAnalysis': 'हथेली के पहाड़ियों का विश्लेषण',
    'palmistry.recommendations': 'सिफारिशें',
    'palmistry.predictions': 'भविष्यवाणियाँ:',
    'palmistry.length': 'लंबाई:',
    'palmistry.depth': 'गहराई:',
    'palmistry.clarity': 'स्पष्टता:',
    'palmistry.shape': 'आकार:',
    'palmistry.presence': 'उपस्थिति:',

    // Palmistry Analysis Content
    'palmistry.lifeLine.long': 'लंबा (कलाई तक फैला हुआ)',
    'palmistry.lifeLine.deep': 'गहरा और अच्छी तरह से चिह्नित',
    'palmistry.lifeLine.clear': 'स्पष्ट बिना किसी ब्रेक के',
    'palmistry.lifeLine.meaning': 'असाधारण जीवन शक्ति, मजबूत स्वास्थ्य और मजबूत जीवन शक्ति को दर्शाता है। आपके पास उल्लेखनीय लचीलापन है और आप लंबी, स्वस्थ जीवन का आनंद ले सकते हैं। गहराई शारीरिक स्टेमिना और सहनशक्ति का सुझाव देती है।',
    'palmistry.lifeLine.prediction1': 'जीवन भर अच्छा स्वास्थ्य',
    'palmistry.lifeLine.prediction2': 'मजबूत प्रतिरक्षा प्रणाली',
    'palmistry.lifeLine.prediction3': 'बीमारियों से त्वरित वसूली',
    'palmistry.lifeLine.prediction4': 'उच्च ऊर्जा स्तर',
    'palmistry.heartLine.curved': 'उंगलियों की ओर ऊपर मुड़ा हुआ',
    'palmistry.heartLine.high': 'हथेली पर उच्च',
    'palmistry.heartLine.unbroken': 'स्पष्ट और अटूट',
    'palmistry.heartLine.meaning': 'गहरी भावनात्मक गहराई, मजबूत रोमांटिक झुकाव और भावुक प्रकृति दिखाता है। आप रिश्तों को गहराई से महत्व देते हैं और भावनाओं को स्वतंत्र रूप से व्यक्त करते हैं। उच्च स्थिति आदर्शवादी प्रेम दृष्टिकोण को दर्शाती है।',
    'palmistry.heartLine.prediction1': 'गहरे, सार्थक रिश्ते',
    'palmistry.heartLine.prediction2': 'मजबूत भावनात्मक बंधन',
    'palmistry.heartLine.prediction3': 'रोमांटिक और भावुक प्रकृति',
    'palmistry.heartLine.prediction4': 'साझेदारियों में वफादारी',
    'palmistry.headLine.clear': 'स्पष्ट और अच्छी तरह से परिभाषित',
    'palmistry.headLine.long': 'लंबा, हथेली के पार फैला हुआ',
    'palmistry.headLine.curved': 'थोड़ा मुड़ा हुआ',
    'palmistry.headLine.meaning': 'तेज बुद्धि, विश्लेषणात्मक सोच क्षमताएं और मजबूत निर्णय लेने की क्षमताएं दर्शाता है। लंबाई व्यापक सोच और विवरण पर ध्यान का सुझाव देती है। थोड़ा मोड़ तर्क और रचनात्मकता के बीच संतुलन दिखाता है।',
    'palmistry.headLine.prediction1': 'उत्कृष्ट समस्या-समाधान क्षमताएं',
    'palmistry.headLine.prediction2': 'बौद्धिक प्रयासों में सफलता',
    'palmistry.headLine.prediction3': 'रणनीतिक सोच',
    'palmistry.headLine.prediction4': 'नेतृत्व क्षमता',
    'palmistry.fateLine.present': 'उपस्थित और मजबूत',
    'palmistry.fateLine.wellDefined': 'अच्छी तरह से परिभाषित',
    'palmistry.fateLine.position': 'कलाई से मध्य उंगली तक चलता है',
    'palmistry.fateLine.meaning': 'स्पष्ट जीवन दिशा, करियर सफलता और मजबूत उद्देश्य की भावना का सुझाव देता है। आपका मार्ग अच्छी तरह से परिभाषित है और आपके पास लक्ष्यों को प्राप्त करने की स्वाभाविक क्षमता है। मजबूत भाग्य रेखा आत्मनिर्भर सफलता को दर्शाती है।',
    'palmistry.fateLine.prediction1': 'करियर में उन्नति',
    'palmistry.fateLine.prediction2': 'वित्तीय स्थिरता',
    'palmistry.fateLine.prediction3': 'लक्ष्यों की प्राप्ति',
    'palmistry.fateLine.prediction4': 'पेशे में मान्यता',
    'palmistry.mount.jupiter': 'नेतृत्व, महत्वाकांक्षा, आत्मविश्वास',
    'palmistry.mount.saturn': 'बुद्धिमत्ता, अनुशासन, जिम्मेदारी',
    'palmistry.mount.apollo': 'रचनात्मकता, सफलता, कलात्मक प्रतिभाएं',
    'palmistry.mount.mercury': 'संचार, व्यापारिक कौशल',
    'palmistry.mount.venus': 'प्रेम, जुनून, जीवन शक्ति',
    'palmistry.mount.luna': 'कल्पना, अंतर्ज्ञान, संवेदनशीलता',
    'palmistry.thumb': 'मजबूत और अच्छी तरह से आनुपातिक - इच्छाशक्ति और दृढ़ता को दर्शाता है',
    'palmistry.index': 'लंबा - नेतृत्व और महत्वाकांक्षा दिखाता है',
    'palmistry.middle': 'संतुलित - स्थिरता और जिम्मेदारी का सुझाव देता है',
    'palmistry.ring': 'प्रमुख - रचनात्मकता और मान्यता की इच्छा को दर्शाता है',
    'palmistry.pinky': 'अच्छी लंबाई - संचार कौशल दिखाती है',
    'palmistry.star': 'तेजस्वी सफलता और मान्यता',
    'palmistry.triangle': 'असाधारण करियर उपलब्धि',
    'palmistry.moneyLine': 'वित्तीय समृद्धि',
    'palmistry.overallAnalysis': 'आपका हस्तरेखा विश्लेषण असाधारण रूप से संतुलित और भाग्यशाली व्यक्तित्व को प्रकट करता है। मजबूत जीवन शक्ति के साथ भावनात्मक गहराई और बौद्धिक क्षमताएं सफलता के लिए एक शक्तिशाली आधार बनाती हैं। अच्छी तरह से परिभाषित भाग्य रेखा और प्रमुख पहाड़ियाँ स्पष्ट जीवन दिशा और कई प्रतिभाओं को दर्शाती हैं। आप स्वाभाविक रूप से नेतृत्व, रचनात्मक प्रयासों और गहरे रिश्तों के निर्माण के लिए सुसज्जित हैं। आपका हस्तरेखा उपलब्धि, अच्छा स्वास्थ्य और भावनात्मक संतुष्टि का जीवन सुझाव देता है।',
    'palmistry.recommendation1': 'अपने करियर में नेतृत्व भूमिकाओं पर ध्यान दें',
    'palmistry.recommendation2': 'अपनी रचनात्मक प्रतिभाओं को आगे विकसित करें',
    'palmistry.recommendation3': 'इष्टतम स्वास्थ्य के लिए कार्य-जीवन संतुलन बनाए रखें',
    'palmistry.recommendation4': 'अपने भावनात्मक संबंधों को पोषित करें',
    'palmistry.recommendation5': 'निर्णय लेने में अपनी अंतर्ज्ञान पर भरोसा करें',

    // Palmistry Analysis Results (Mock Data)
    'palmistry.analysis.lifeLine.length': 'लंबा (कलाई तक फैला हुआ)',
    'palmistry.analysis.lifeLine.depth': 'गहरा और अच्छी तरह से चिह्नित',
    'palmistry.analysis.lifeLine.clarity': 'स्पष्ट बिना किसी ब्रेक के',
    'palmistry.analysis.lifeLine.meaning': 'असाधारण जीवन शक्ति, मजबूत स्वास्थ्य और मजबूत जीवन शक्ति को दर्शाता है। आपके पास उल्लेखनीय लचीलापन है और आप लंबी, स्वस्थ जीवन का आनंद ले सकते हैं। गहराई शारीरिक स्टेमिना और सहनशक्ति का सुझाव देती है।',
    'palmistry.analysis.lifeLine.prediction1': 'जीवन भर अच्छा स्वास्थ्य',
    'palmistry.analysis.lifeLine.prediction2': 'मजबूत प्रतिरक्षा प्रणाली',
    'palmistry.analysis.lifeLine.prediction3': 'बीमारियों से त्वरित वसूली',
    'palmistry.analysis.lifeLine.prediction4': 'उच्च ऊर्जा स्तर',
    'palmistry.analysis.heartLine.shape': 'उंगलियों की ओर ऊपर मुड़ा हुआ',
    'palmistry.analysis.heartLine.position': 'हथेली पर उच्च',
    'palmistry.analysis.heartLine.clarity': 'स्पष्ट और अटूट',
    'palmistry.analysis.heartLine.meaning': 'गहरी भावनात्मक गहराई, मजबूत रोमांटिक झुकाव और भावुक प्रकृति दिखाता है। आप रिश्तों को गहराई से महत्व देते हैं और भावनाओं को स्वतंत्र रूप से व्यक्त करते हैं। उच्च स्थिति आदर्शवादी प्रेम दृष्टिकोण को दर्शाती है।',
    'palmistry.analysis.heartLine.prediction1': 'गहरे, सार्थक रिश्ते',
    'palmistry.analysis.heartLine.prediction2': 'मजबूत भावनात्मक बंधन',
    'palmistry.analysis.heartLine.prediction3': 'रोमांटिक और भावुक प्रकृति',
    'palmistry.analysis.heartLine.prediction4': 'साझेदारियों में वफादारी',
    'palmistry.analysis.headLine.clarity': 'स्पष्ट और अच्छी तरह से परिभाषित',
    'palmistry.analysis.headLine.length': 'लंबा, हथेली के पार फैला हुआ',
    'palmistry.analysis.headLine.curve': 'थोड़ा मुड़ा हुआ',
    'palmistry.analysis.headLine.meaning': 'तेज बुद्धि, विश्लेषणात्मक सोच क्षमताएं और मजबूत निर्णय लेने की क्षमताएं दर्शाता है। लंबाई व्यापक सोच और विवरण पर ध्यान का सुझाव देती है। थोड़ा मोड़ तर्क और रचनात्मकता के बीच संतुलन दिखाता है।',
    'palmistry.analysis.headLine.prediction1': 'उत्कृष्ट समस्या-समाधान क्षमताएं',
    'palmistry.analysis.headLine.prediction2': 'बौद्धिक प्रयासों में सफलता',
    'palmistry.analysis.headLine.prediction3': 'रणनीतिक सोच',
    'palmistry.analysis.headLine.prediction4': 'नेतृत्व क्षमता',
    'palmistry.analysis.fateLine.presence': 'उपस्थित और मजबूत',
    'palmistry.analysis.fateLine.clarity': 'अच्छी तरह से परिभाषित',
    'palmistry.analysis.fateLine.position': 'कलाई से मध्य उंगली तक चलता है',
    'palmistry.analysis.fateLine.meaning': 'स्पष्ट जीवन दिशा, करियर सफलता और मजबूत उद्देश्य की भावना का सुझाव देता है। आपका मार्ग अच्छी तरह से परिभाषित है और आपके पास लक्ष्यों को प्राप्त करने की स्वाभाविक क्षमता है। मजबूत भाग्य रेखा आत्मनिर्भर सफलता को दर्शाती है।',
    'palmistry.analysis.fateLine.prediction1': 'करियर में उन्नति',
    'palmistry.analysis.fateLine.prediction2': 'वित्तीय स्थिरता',
    'palmistry.analysis.fateLine.prediction3': 'लक्ष्यों की प्राप्ति',
    'palmistry.analysis.fateLine.prediction4': 'पेशे में मान्यता',
    'palmistry.analysis.mounts.jupiter.prominence': 'अच्छी तरह से विकसित',
    'palmistry.analysis.mounts.jupiter.meaning': 'नेतृत्व, महत्वाकांक्षा, आत्मविश्वास',
    'palmistry.analysis.mounts.saturn.prominence': 'संतुलित',
    'palmistry.analysis.mounts.saturn.meaning': 'बुद्धिमत्ता, अनुशासन, जिम्मेदारी',
    'palmistry.analysis.mounts.apollo.prominence': 'प्रमुख',
    'palmistry.analysis.mounts.apollo.meaning': 'रचनात्मकता, सफलता, कलात्मक प्रतिभाएं',
    'palmistry.analysis.mounts.mercury.prominence': 'मध्यम',
    'palmistry.analysis.mounts.mercury.meaning': 'संचार, व्यापारिक कौशल',
    'palmistry.analysis.mounts.venus.prominence': 'पूर्ण',
    'palmistry.analysis.mounts.venus.meaning': 'प्रेम, जुनून, जीवन शक्ति',
    'palmistry.analysis.mounts.luna.prominence': 'विकसित',
    'palmistry.analysis.mounts.luna.meaning': 'कल्पना, अंतर्ज्ञान, संवेदनशीलता',
    'palmistry.analysis.fingerAnalysis.thumb': 'मजबूत और अच्छी तरह से आनुपातिक - इच्छाशक्ति और दृढ़ता को दर्शाता है',
    'palmistry.analysis.fingerAnalysis.index': 'लंबा - नेतृत्व और महत्वाकांक्षा दिखाता है',
    'palmistry.analysis.fingerAnalysis.middle': 'संतुलित - स्थिरता और जिम्मेदारी का सुझाव देता है',
    'palmistry.analysis.fingerAnalysis.ring': 'प्रमुख - रचनात्मकता और मान्यता की इच्छा को दर्शाता है',
    'palmistry.analysis.fingerAnalysis.pinky': 'अच्छी लंबाई - संचार कौशल दिखाती है',
    'palmistry.analysis.specialMarks.star': 'तेजस्वी सफलता और मान्यता',
    'palmistry.analysis.specialMarks.triangle': 'असाधारण करियर उपलब्धि',
    'palmistry.analysis.specialMarks.moneyLine': 'वित्तीय समृद्धि',
    'palmistry.analysis.overall': 'आपका हस्तरेखा विश्लेषण असाधारण रूप से संतुलित और भाग्यशाली व्यक्तित्व को प्रकट करता है। मजबूत जीवन शक्ति के साथ भावनात्मक गहराई और बौद्धिक क्षमताएं सफलता के लिए एक शक्तिशाली आधार बनाती हैं। अच्छी तरह से परिभाषित भाग्य रेखा और प्रमुख पहाड़ियाँ स्पष्ट जीवन दिशा और कई प्रतिभाओं को दर्शाती हैं। आप स्वाभाविक रूप से नेतृत्व, रचनात्मक प्रयासों और गहरे रिश्तों के निर्माण के लिए सुसज्जित हैं। आपका हस्तरेखा उपलब्धि, अच्छा स्वास्थ्य और भावनात्मक संतुष्टि का जीवन सुझाव देता है।',
    'palmistry.analysis.recommendations.1': 'अपने करियर में नेतृत्व भूमिकाओं पर ध्यान दें',
    'palmistry.analysis.recommendations.2': 'अपनी रचनात्मक प्रतिभाओं को आगे विकसित करें',
    'palmistry.analysis.recommendations.3': 'इष्टतम स्वास्थ्य के लिए कार्य-जीवन संतुलन बनाए रखें',
    'palmistry.analysis.recommendations.4': 'अपने भावनात्मक संबंधों को पोषित करें',
    'palmistry.analysis.recommendations.5': 'निर्णय लेने में अपनी अंतर्ज्ञान पर भरोसा करें',

    // Kundali Page
    'kundali.birthDetails': 'जन्म विवरण',
    'kundali.fullName': 'पूरा नाम',
    'kundali.day': 'दिन',
    'kundali.month': 'माह',
    'kundali.year': 'साल',
    'kundali.hour': 'घंटा (24 घंटे)',
    'kundali.minute': 'मिनट',
    'kundali.placeOfBirth': 'जन्म स्थान',
    'kundali.selectCity': 'एक शहर चुनें',
    'kundali.manualLocation': 'स्थान मैन्युअल रूप से दर्ज करें',
    'kundali.cityTown': 'शहर/गाँव',
    'kundali.latitude': 'अक्षांश',
    'kundali.longitude': 'देशांतर',
    'kundali.generateKundali': 'कुंडली तैयार करें',
    'kundali.generating': 'तैयार हो रहा है...',
    'kundali.exportPDF': 'PDF के रूप में निर्यात करें',
    'kundali.exporting': 'निर्यात हो रहा है...',
    'kundali.basicDetails': 'मूल विवरण',
    'kundali.sunSign': 'सूर्य राशि',
    'kundali.moonSign': 'चंद्र राशि',
    'kundali.ascendant': 'लग्न',
    'kundali.rashi': 'राशि',
    'kundali.nakshatras': 'नक्षत्र',
    'kundali.sunNakshatra': 'सूर्य नक्षत्र:',
    'kundali.moonNakshatra': 'चंद्र नक्षत्र:',
    'kundali.ascendantNakshatra': 'लग्न नक्षत्र:',
    'kundali.pada': 'पदा:',
    'kundali.characteristics': 'विशेषताएँ:',
    'kundali.planetaryPositions': 'ग्रहों की स्थिति',
    'kundali.benefic': 'हितकारी',
    'kundali.malefic': 'अहितकारी',
    'kundali.sign': 'राशि:',
    'kundali.house': 'घर:',
    'kundali.degree': 'डिग्री:',
    'kundali.nakshatra': 'नक्षत्र:',
    'kundali.retrograde': 'वक्री',
    'kundali.planetaryStrengths': 'ग्रहों की शक्तियाँ',
    'kundali.status': 'स्थिति:',
    'kundali.strengthPercent': 'शक्ति प्रतिशत:',
    'kundali.shadbala': 'षड्बल:',
    'kundali.currentDasha': 'वर्तमान दशा अवधि',
    'kundali.mahadasha': 'महादशा',
    'kundali.level': 'स्तर:',
    'kundali.period': 'अवधि:',
    'kundali.upcomingMahadashas': 'आगामी महादशाएँ',
    'kundali.auspiciousYogas': 'शुभ योग',
    'kundali.strength': 'शक्ति:',
    'kundali.planets': 'ग्रह:',
    'kundali.doshasMalefic': 'दोष और अहितकारी प्रभाव',
    'kundali.present': 'उपस्थित',
    'kundali.absent': 'अनुपस्थित',
    'kundali.active': 'सक्रिय',
    'kundali.inactive': 'निष्क्रिय',
    'kundali.mangalDosha': 'मंगल दोष',
    'kundali.kalSarpDosha': 'काल सर्प दोष',
    'kundali.pitruDosha': 'पितृ दोष',
    'kundali.sadeSati': 'साढ़े साती',
    'kundali.lifePredictions': 'जीवन भविष्यवाणियाँ',
    'kundali.personality': 'व्यक्तित्व',
    'kundali.career': 'करियर',
    'kundali.finance': 'वित्त',
    'kundali.health': 'स्वास्थ्य',
    'kundali.marriage': 'विवाह और संबंध',
    'kundali.education': 'शिक्षा',
    'kundali.recommendedRemedies': 'अनुशंसित उपाय',
    'kundali.note': 'Note:',
    'kundali.languageToggle': 'भाषा बदलें',
    'kundali.languageEnglish': 'English',
    'kundali.languageHindi': 'हिंदी',
    'kundali.saveKundali': 'कुंडली सहेजें',
    'kundali.saving': 'सहेज रहा है...',
    'kundali.namePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'kundali.dayPlaceholder': 'DD',
    'kundali.monthPlaceholder': 'MM',
    'kundali.yearPlaceholder': 'YYYY',
    'kundali.hourPlaceholder': 'HH',
    'kundali.minutePlaceholder': 'MM',
    'kundali.cityPlaceholder': 'एक शहर चुनें',
    'kundali.manualCityPlaceholder': 'शहर या गाँव का नाम दर्ज करें',
    'kundali.manualLocationText': 'स्थान मैन्युअल रूप से दर्ज करें',
    'kundali.ampm': 'AM/PM',
    'kundali.generatingText': 'तैयार हो रहा है...',
    'kundali.generateText': 'कुंडली तैयार करें',
    'kundali.exportText': 'PDF के रूप में निर्यात करें',
    'kundali.exportingText': 'निर्यात हो रहा है...',
    'kundali.saveText': 'कुंडली सहेजें',
    'kundali.savingText': 'सहेज रहा है...',
    'kundali.basicDetailsTitle': 'मूल विवरण',
    'kundali.nakshatrasTitle': 'नक्षत्र',
    'kundali.planetaryPositionsTitle': 'ग्रहों की स्थिति',
    'kundali.planetaryStrengthsTitle': 'ग्रहों की शक्तियाँ',
    'kundali.currentDashaTitle': 'वर्तमान दशा अवधि',
    'kundali.auspiciousYogasTitle': 'शुभ योग',
    'kundali.doshasTitle': 'दोष और अहितकारी प्रभाव',
    'kundali.lifePredictionsTitle': 'जीवन भविष्यवाणियाँ',
    'kundali.remediesTitle': 'अनुशंसित उपाय',
    'kundali.sunSignLabel': 'सूर्य राशि',
    'kundali.moonSignLabel': 'चंद्र राशि',
    'kundali.ascendantLabel': 'लग्न',
    'kundali.rashiLabel': 'नाम राशि',
    'kundali.beneficLabel': 'हितकारी',
    'kundali.maleficLabel': 'अहितकारी',
    'kundali.retrogradeLabel': 'वक्री',
    'kundali.statusLabel': 'स्थिति',
    'kundali.strengthPercentLabel': 'शक्ति प्रतिशत',
    'kundali.shadbalaLabel': 'षड्बल',
    'kundali.levelLabel': 'स्तर',
    'kundali.periodLabel': 'अवधि',
    'kundali.upcomingLabel': 'आगामी महादशाएँ',
    'kundali.strengthLabel': 'शक्ति',
    'kundali.planetsLabel': 'ग्रह',
    'kundali.presentLabel': 'उपस्थित',
    'kundali.absentLabel': 'अनुपस्थित',
    'kundali.activeLabel': 'सक्रिय',
    'kundali.inactiveLabel': 'निष्क्रिय',
    'kundali.mangalDoshaLabel': 'मंगल दोष',
    'kundali.kalSarpDoshaLabel': 'काल सर्प दोष',
    'kundali.pitruDoshaLabel': 'पितृ दोष',
    'kundali.sadeSatiLabel': 'साढ़े साती',
    'kundali.personalityLabel': 'व्यक्तित्व',
    'kundali.careerLabel': 'करियर',
    'kundali.financeLabel': 'वित्त',
    'kundali.healthLabel': 'स्वास्थ्य',
    'kundali.marriageLabel': 'विवाह और संबंध',
    'kundali.educationLabel': 'शिक्षा',
    'kundali.noteLabel': 'नोट:',
    'kundali.remedyNote': 'ये उपाय आपके जन्म कुंडली के आधार पर सामान्य सुझाव हैं। व्यक्तिगत मार्गदर्शन के लिए योग्य ज्योतिषी से परामर्श करें और इन उपायों को ठीक से लागू करें।',
    // About Page
    'about.value1.title': 'प्रामाणिकता',
    'about.value1.desc': 'हम प्राचीन बुद्धिमत्ता और आधुनिक सटीकता के आधार पर वास्तविक वैदिक ज्योतिष सेवाएं प्रदान करते हैं।',
    'about.value2.title': 'समुदाय',
    'about.value2.desc': 'हमारे बढ़ते समुदाय में शामिल हों जहां ज्योतिष के माध्यम से मार्गदर्शन और परिवर्तन पाने वाले खोजकर्ताओं ने भाग लिया है।',
    'about.value3.title': 'उत्कृष्टता',
    'about.value3.desc': 'हम ज्योतिष अभ्यास में उच्चतम मानकों को बनाए रखते हैं, सटीक और विश्वसनीय भविष्यवाणियों को सुनिश्चित करते हैं।',
    'about.value4.title': 'सहानुभूति',
    'about.value4.desc': 'हर परामर्श में सहानुभूति, समझ और आपके कल्याण के लिए वास्तविक देखभाल के साथ संपर्क किया जाता है।',
    'about.value5.title': 'विश्वास',
    'about.value5.desc': 'आपकी गोपनीयता और सुरक्षा सर्वोपरि है, सभी परामर्श पूर्ण विश्वास में किए जाते हैं।',
    'about.value6.title': 'नवाचार',
    'about.value6.desc': 'हम पारंपरिक बुद्धिमत्ता को आधुनिक तकनीक के साथ मिलाते हैं ताकि ज्योतिष सुलभ और सुविधाजनक हो सके।',
    'about.stats1': 'खुश उपयोगकर्ता',
    'about.stats2': 'विशेषज्ञ ज्योतिषी',
    'about.stats3': 'साल का अनुभव',
    'about.stats4': 'सटीकता दर',
    'about.ourStory': 'हमारी कहानी\n\nविप्रकर्मा वैदिक ज्योतिष और आधुनिक दुनिया को सुलभ बनाने के लिए गहरी जुनून से पैदा हुआ। हमारे संस्थापक, स्वयं अनुभवी ज्योतिषी, ने पारंपरिक ज्योतिषीय परामर्श और तेजी से डिजिटल युग के बीच की खाई को पहचाना।\n\nहमने प्रमाणित ज्योतिषियों, कुशल डेवलपर्स और डिजाइन विशेषज्ञों की टीम एकत्र की ताकि एक ऐसा प्लेटफर्म बनाया जा सके जो दोनों दुनिया के सर्वश्रेष्ठ को जोड़ता है - वैदिक ज्योतिष की गहरी बुद्धिमत्ता और आधुनिक तकनीक की सुविधा।\n\nआज, हम दुनिया भर में हजारों उपयोगकर्ताओं की सेवा करते हैं, उन्हें जीवन की चुनौतियों को खगोलीय मार्गदर्शन के साथ नेविगेट करने में मदद करते हैं। चाहे वह करियर निर्णय हों, रिश्तों के प्रश्न, स्वास्थ्य चिंताएं या आध्यात्मिक विकास, हम आपके मार्ग को ज्योतिषीय बुद्धिमत्ता की रोशनी से प्रकाशित करने के लिए यहां हैं।',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('hi');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'hi')) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    if (mounted) {
      localStorage.setItem('language', language);
    }
  }, [language, mounted]);

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === 'en' ? 'hi' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
