import { db } from '@/db';
import { pandits } from '@/db/schema';

async function main() {
    const samplePandits = [
        {
            name: 'Pandit Rajesh Sharma',
            specialization: 'Vedic Rituals & Pujas',
            experience: 18,
            languages: 'Hindi, English, Sanskrit',
            rating: 4.8,
            pricePerHour: 1800,
            location: 'Mumbai',
            description: 'Expert in traditional Vedic rituals with deep knowledge of ancient scriptures. Specializes in complex pujas and havans for various occasions.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Acharya Suresh Joshi',
            specialization: 'Marriage Ceremonies (Vivah Sanskar)',
            experience: 22,
            languages: 'Hindi, Marathi, Sanskrit',
            rating: 4.9,
            pricePerHour: 2500,
            location: 'Pune',
            description: 'Renowned marriage ceremony specialist with over two decades of experience. Conducts traditional Hindu weddings with authentic rituals.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Shastri Ramesh Iyer',
            specialization: 'Griha Pravesh',
            experience: 12,
            languages: 'Hindi, Tamil, Sanskrit',
            rating: 4.6,
            pricePerHour: 1200,
            location: 'Chennai',
            description: 'Specialized in house warming ceremonies and Vastu-compliant Griha Pravesh rituals. Known for precise muhurat selection.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pandit Vijay Kumar',
            specialization: 'Satyanarayan Katha',
            experience: 8,
            languages: 'Hindi, English, Sanskrit',
            rating: 4.5,
            pricePerHour: 800,
            location: 'Delhi',
            description: 'Dedicated to performing Satyanarayan Katha with devotion and proper rituals. Creates peaceful and spiritual atmosphere.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Guru Prakash Mishra',
            specialization: 'Navgraha Shanti',
            experience: 25,
            languages: 'Hindi, Bengali, Sanskrit',
            rating: 5.0,
            pricePerHour: 2200,
            location: 'Kolkata',
            description: 'Master of planetary remedies and Navgraha Shanti pujas. Provides personalized solutions based on Vedic astrology.',
            imageUrl: null,
            available: false,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pandit Mahesh Pandey',
            specialization: 'Rudrabhishek',
            experience: 15,
            languages: 'Hindi, English, Sanskrit',
            rating: 4.7,
            pricePerHour: 1500,
            location: 'Bangalore',
            description: 'Expert in performing Rudrabhishek and Shiv pujas. Known for powerful mantras and authentic Shaivite rituals.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Acharya Deepak Trivedi',
            specialization: 'General Puja and Ceremonies',
            experience: 10,
            languages: 'Hindi, Gujarati, Sanskrit',
            rating: 4.4,
            pricePerHour: 1000,
            location: 'Ahmedabad',
            description: 'Versatile pandit skilled in various Hindu rituals and ceremonies. Available for all types of religious occasions.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pandit Anil Shastri',
            specialization: 'Vastu Shastra and Remedies',
            experience: 20,
            languages: 'Hindi, English, Sanskrit',
            rating: 4.9,
            pricePerHour: 2000,
            location: 'Jaipur',
            description: 'Vastu expert providing comprehensive solutions for homes and businesses. Combines traditional knowledge with practical remedies.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pandit Krishna Dwivedi',
            specialization: 'Death Rituals (Antim Sanskar)',
            experience: 6,
            languages: 'Hindi, Telugu, English, Sanskrit',
            rating: 4.3,
            pricePerHour: 600,
            location: 'Hyderabad',
            description: 'Compassionate and knowledgeable in performing last rites and death ceremonies according to Hindu traditions.',
            imageUrl: null,
            available: false,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Shastri Gopal Tiwari',
            specialization: 'Thread Ceremony (Upanayana)',
            experience: 14,
            languages: 'Hindi, English, Sanskrit',
            rating: 4.7,
            pricePerHour: 1300,
            location: 'Lucknow',
            description: 'Traditional Brahmin scholar specializing in sacred thread ceremonies. Ensures proper mantras and rituals are followed.',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'पंडित विष्णुश्री कृष्णतनय महाराज (गुर्जी)',
            specialization: 'अथर्ववेदी, भागवताचार्य, (भागवत कथा, रामकथा, नानीबाई रो मायरो, शिवमहापुराण, रुक्मिणी - मंगल,)',
            experience: 15,
            languages: 'हिंदी',
            rating: 4.5,
            pricePerHour: 3000,
            location: 'Bengaluru',
            description: 'विगत 15 वर्षों से कथा और कर्मकांड, ज्योतिष प्रकोष्ठ का कार्यानुभव। सोशल मोटिवेटर, ज्योतिष प्रकोष्ठ।',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'आचार्य सुनील पाठक',
            specialization: 'सर्व धर्म समभाव, ज्योतिष प्रकोष्ठ',
            experience: 20,
            languages: 'हिंदी, संस्कृत',
            rating: 4.5,
            pricePerHour: 3000,
            location: 'Bengaluru',
            description: 'शास्त्री और आचार्य की डिग्री प्राप्त। 20 वर्षों का अनुभव। ये नहीं कि हम भाग्य बदल सकते किन्तु ईश्वरवाद का सहारा लेकर आपको तड़पती हुई उलझी हुई तथा ठहरी हुई अव्यवस्था से मुक्ति उन्नति पथ को प्रशस्त करने मे सहयोग कर सकते।',
            imageUrl: null,
            available: true,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(pandits).values(samplePandits);
    
    console.log('✅ Pandits seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});